domains:
  - name: example.com
    proxied: true
    ipv4: true
    ipv6: false
    ttl: auto

  - name: *.example.com
    proxied: false
    ipv4: true
    ipv6: true
    ttl: 120

settings:
  cloudflare:
    zone_id: your_zone_id_here
    zone_api_token: your_api_token_here
  notifications:
    telegram:
      enabled: false
      bot_token: ""
      chat_id: ""
    discord:
      enabled: false
      webhook_url: ""
