name: Unit Test and Coverage Report

on:
  workflow_call:
    inputs:
      OS:
        required: true
        type: string
      RUBY:
        required: true
        type: string
      BUNDLE_GEMFILE:
        required: true
        type: string

permissions:
  contents: read

jobs:

  checkout:
    name: Run Unit Tests and Coverage Report
    runs-on: ${{ inputs.OS }}
    env:
      BUNDLE_GEMFILE: ${{ inputs.BUNDLE_GEMFILE }}
    steps:
      - name: Checkout repository with all submodules
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 3
          submodules: recursive

      - name: Get Ruby
        uses: ruby/setup-ruby@3783f195e29b74ae398d7caca108814bbafde90e # v1.180.1
        with:
          ruby-version: ${{ inputs.RUBY }}
      - name: Install Gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
        shell: bash

      - name: Prepare scripts
        run: |
          chmod +x cloudflare-dns.sh
          chmod +x unit-test.sh
        shell: bash
      - name: Run Unit Tests
        run: |
          bashcov -s ./unit-test.sh
        shell: bash

      - name: Upload reports to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: OS_${{ inputs.OS }}__Ruby_${{ inputs.RUBY }}
          #functionalities: gcov
          os: ${{ inputs.OS }}
          name: "DynDNS Cloudflare - OS: ${{ inputs.OS }} ; RUBY: ${{ inputs.RUBY }}"
          verbose: true

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage/coverage.xml
          language: Shell
